project:
  type: book
  output-dir: docs

book:
  title: "Linux ir programavimas"
  author: "Justas Mundeikis"
  chapters:
    - part: "Linux Basics"
      chapters:
        - index.qmd
        - 1_linux_configure.qmd
        - 2_linux_update.qmd
        - 3_linux_software.qmd
    - part: "Bash and Terminal"
      chapters:
        - 5_terminal_filesystem.qmd
        - 6_bash_comands_basic.qmd
        - 7_bash_comands_advanced.qmd
        - 8_bash_advanced2.qmd
    - part: "Text Editing and Git"
      chapters:
        - 9_text_editor_ide.qmd
        - 10_git_github_1.qmd
        - 11_git_github_2.qmd
        - 11b_ssh.qmd
    - part: "Python Programming"
      chapters:
        - 12_python_intro.qmd
        - 13_python_data_structures_loops.qmd
        - 14_python_variables_conditionals.qmd
        - 15_python_read_write_files.qmd
        - 16_python_APIs.qmd
        - 17_python_functions_os.qmd
        - 18_Python_openai_api.qmd
    - part: "Advanced Topics"
      chapters:
        - 26_TCP_IP.qmd
        - 27_raspberry_pi.qmd
        - 28_home_server.qmd
        - 29_docker_1.qmd
        - 30_docker_2.qmd

format:
  html:
    theme: flatly



