project:
  type: book
  output-dir: docs

book:
  title: "Linux ir programavimas"
  author: "Justas Mundeikis"
  chapters:
    - part: "Linux Pagrindai"
      chapters:
        - index.qmd
        - 1_linux_configure.qmd
        - 2_linux_update.qmd
        - 3_linux_software.qmd
        - 4_passwords.qmd
    - part: "Bash Pagrindai"
      chapters:
        - 5_bash_terminal_filesystem.qmd
        - 6_bash_comands_basic.qmd
        - 7_bash_comands_advanced_1.qmd
        - 8_bash_commands_advanced_2.qmd
    - part: "Editoriai ir Git"
      chapters:
        - 9_text_editors_ide.qmd
        - 10_git_github_1.qmd
        - 11_git_github_2.qmd
        - 12_ssh.qmd
    - part: "Bash Skriptai"
      chapters:
        - 14_bash_scripts_1.qmd
        - 15_bash_scripts_2.qmd
    - part: "Python Programavimas"
      chapters:
        - 12_python_intro.qmd
        - 16a_python_data_structures_loops.qmd
        - 16b_python_variables_conditionals.qmd
        - 16c_python_read_write_files.qmd
        - 16_python_APIs.qmd
        - 17_python_functions_os.qmd
        - 18_Python_openai_api.qmd
        - 19_python_webscrapping.qmd
        - 20_python_ollama.qmd
        - 21_python_bottles.qmd
        - 22_python_sql.qmd
        - 23_python_html.qmd
        - 24_python_css.qmd
        - 25_python_deployment.qmd
    - part: "Pažangios Temos"
      chapters:
        - 26_TCP_IP.qmd
        - 27_raspberry_pi.qmd
        - 28_home_server.qmd
        - 29_docker_1.qmd
        - 30_docker_2.qmd

format:
  html:
    theme: flatly