project:
  type: book
  output-dir: docs

book:
  title: "Linux vaikams ir pradedantiesiems"
  author: "Justas Mundeikis"
  chapters:
    - index.qmd
    - 1_intro_terminal.qmd
    - 2_linux_programm_update_install_remove.qmd

format:
  html:
    theme: flatly



