project:
  type: book
  output-dir: docs

book:
  title: "Linux vaikams ir pradedantiesiems"
  author: "Justas Mundeikis"
  chapters:
    - index.qmd
    - 1_linux_configure.qmd
    - 3_linux_update.qmd
    - 4_linux_software.qmd
    - 5_passwords_online_accounts.qmd
    - 6a_linux_comands_basic.qmd
    - 6b_linux_comands_basic.qmd
    - 7_linux_comands_advanced.qmd

format:
  html:
    theme: flatly



